export const mockOrderList = {
  new: [1, 2, 3, 4, 5],
  accepted: [1, 2, 3, 4, 5],
  ready: [1, 2, 3, 4, 5],
  on_a_way: [1, 2, 3, 4, 5],
  delivered: [1, 2, 3, 4, 5],
  canceled: [1, 2, 3, 4, 5],
  cooking: [1, 2, 3, 4, 5],
};

export const transactionStatuses = [
  'progress',
  'paid',
  'canceled',
  'rejected',
  'refund',
];

export const orderPayments = ['before', 'after'];

export const LOCALE_COLORS = ['blue', 'red', 'gold', 'volcano', 'cyan', 'lime'];

export const ORDER_DETAILS_STATUSES = [
  'new',
  'accepted',
  'cooking',
  'ready',
  'ended',
];

export const SHOP_EMAIL_STATUSES = [
  'new',
  'accepted',
  'cooking',
  'ready',
  'on_a_way',
  'delivered',
  'canceled',
];

export const ORDER_TYPES = ['dine_in', 'delivery', 'pickup'];

export const userGenders = ['male', 'female'];

export const PRODUCT_TYPES = ['single', 'combo'];
export const MODELS = {
  ActiveReferral: 'ActiveReferral',
  AdsPackage: 'AdsPackage',
  AILog: 'AILog',
  Area: 'Area',
  AssignShopTag: 'AssignShopTag',
  Auction: 'Auction',
  AuctionQuestion: 'AuctionQuestion',
  AuctionUser: 'AuctionUser',
  BackupHistory: 'BackupHistory',
  Banner: 'Banner',
  BannerProduct: 'BannerProduct',
  Blog: 'Blog',
  Bonus: 'Bonus',
  Booking: 'Booking',
  BookingActivity: 'BookingActivity',
  BookingCoupon: 'BookingCoupon',
  BookingExtra: 'BookingExtra',
  BookingExtraTime: 'BookingExtraTime',
  Brand: 'Brand',
  Career: 'Career',
  Cart: 'Cart',
  CartDetail: 'CartDetail',
  CartDetailProduct: 'CartDetailProduct',
  Category: 'Category',
  City: 'City',
  Country: 'Country',
  Coupon: 'Coupon',
  Currency: 'Currency',
  DeliveryManSetting: 'DeliveryManSetting',
  DeliveryPoint: 'DeliveryPoint',
  DeliveryPointClosedDate: 'DeliveryPointClosedDate',
  DeliveryPointWorkingDay: 'DeliveryPointWorkingDay',
  DeliveryPrice: 'DeliveryPrice',
  DigitalFile: 'DigitalFile',
  Discount: 'Discount',
  EmailSetting: 'EmailSetting',
  EmailSubscription: 'EmailSubscription',
  EmailTemplate: 'EmailTemplate',
  ExtraGroup: 'ExtraGroup',
  ExtraValue: 'ExtraValue',
  Faq: 'Faq',
  FormOption: 'FormOption',
  Gallery: 'Gallery',
  GiftCart: 'GiftCart',
  Invitation: 'Invitation',
  LandingPage: 'LandingPage',
  Language: 'Language',
  Like: 'Like',
  MasterClosedDate: 'MasterClosedDate',
  MasterDisabledTime: 'MasterDisabledTime',
  MemberShip: 'MemberShip',
  MemberShipService: 'MemberShipService',
  MetaTag: 'MetaTag',
  ModelLog: 'ModelLog',
  Notification: 'Notification',
  NotificationUser: 'NotificationUser',
  Order: 'Order',
  OrderCoupon: 'OrderCoupon',
  OrderDetail: 'OrderDetail',
  OrderRefund: 'OrderRefund',
  OrderStatus: 'OrderStatus',
  OrderStatusNote: 'OrderStatusNote',
  Page: 'Page',
  ParcelOption: 'ParcelOption',
  ParcelOrder: 'ParcelOrder',
  ParcelOrderSetting: 'ParcelOrderSetting',
  Payment: 'Payment',
  PaymentPayload: 'PaymentPayload',
  PaymentProcess: 'PaymentProcess',
  PaymentToPartner: 'PaymentToPartner',
  Payout: 'Payout',
  Receipt: 'Receipt',
  Point: 'Point',
  PointHistory: 'PointHistory',
  PrivacyPolicy: 'PrivacyPolicy',
  Product: 'Product',
  ProductProperty: 'ProductProperty',
  PropertyGroup: 'PropertyGroup',
  PropertyValue: 'PropertyValue',
  PushNotification: 'PushNotification',
  Referral: 'Referral',
  Region: 'Region',
  RequestModel: 'RequestModel',
  Review: 'Review',
  Room: 'Room',
  RoomPrice: 'RoomPrice',
  Service: 'Service',
  ServiceExtra: 'ServiceExtra',
  ServiceFaq: 'ServiceFaq',
  ServiceMaster: 'ServiceMaster',
  ServiceMasterNotification: 'ServiceMasterNotification',
  ServiceMasterPrice: 'ServiceMasterPrice',
  Settings: 'Settings',
  Shop: 'Shop',
  ShopAdsPackage: 'ShopAdsPackage',
  ShopAdsProduct: 'ShopAdsProduct',
  ShopClosedDate: 'ShopClosedDate',
  ShopDeliverymanSetting: 'ShopDeliverymanSetting',
  ShopGallery: 'ShopGallery',
  ShopLocation: 'ShopLocation',
  ShopPayment: 'ShopPayment',
  ShopSocial: 'ShopSocial',
  ShopSubscription: 'ShopSubscription',
  ShopTag: 'ShopTag',
  ShopWorkingDay: 'ShopWorkingDay',
  SmsGateway: 'SmsGateway',
  SmsPayload: 'SmsPayload',
  SocialProvider: 'SocialProvider',
  Stock: 'Stock',
  StockExtra: 'StockExtra',
  Story: 'Story',
  Subscription: 'Subscription',
  Tag: 'Tag',
  TermCondition: 'TermCondition',
  Ticket: 'Ticket',
  Transaction: 'Transaction',
  Translation: 'Translation',
  Unit: 'Unit',
  User: 'User',
  UserActivity: 'UserActivity',
  UserAddress: 'UserAddress',
  UserCart: 'UserCart',
  UserDigitalFile: 'UserDigitalFile',
  UserGiftCart: 'UserGiftCart',
  UserMemberShip: 'UserMemberShip',
  UserPoint: 'UserPoint',
  UserWorkingDay: 'UserWorkingDay',
  Wallet: 'Wallet',
  WalletHistory: 'WalletHistory',
  Warehouse: 'Warehouse',
  WarehouseClosedDate: 'WarehouseClosedDate',
  WarehouseWorkingDay: 'WarehouseWorkingDay',
  WholeSalePrice: 'WholeSalePrice',
};
